#cloud-config
# Some examples here:
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
package_update: true
packages:
  - docker.io
runcmd:
  - cd /root
  - docker run -d -p 80:80 nginx
